feign:
  client:
    config:
      users-api:
        connectTimeout: 65000
        readTimeout: 65000
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: FULL
  url:
    user-api: 'http://localhost:8081/api/v1/auth'
    answer-api: 'http://localhost:8082/admin/answer'
    #    media-api: ''
    messenger-api: 'http://localhost:8083/messenger'
